global:
  scrape_interval: 15s

scrape_configs:
  - job_name: surespot-backend
    static_configs:
      - targets: ['app:3000']
        labels:
          group: surespot-backend
          stack: prod
          service: surespot-backend-prod
    metrics_path: /metrics
